"""
Step 1 + 2 of the image scrape.

- Reads the WordPress sitemaps and the REST API (pages, posts, media, categories)
- Saves raw API JSON to scrape/api/
- Writes scrape/urls.txt (real pages) and lists sitemap spam separately

Run from the repo root:  python3 scripts/scrape/01-urls-and-media.py
"""
import json
import re
import time
import subprocess
from pathlib import Path

SITE = "https://skeinteriors.com"
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "scrape"
API = OUT / "api"
API.mkdir(parents=True, exist_ok=True)
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36"
DELAY = 0.5  # be polite: one request at a time


def get(url):
    """GET via curl (the server's firewall returns 406 to Python's urllib)."""
    time.sleep(DELAY)
    r = subprocess.run(
        ["curl", "-sSL", "--max-time", "90", "-A", UA, "-w", "\\n%{http_code}", url],
        capture_output=True,
    )
    body, _, code = r.stdout.rpartition(b"\n")
    return int(code or 0), body


def paginate(endpoint):
    """Fetch every page of a REST collection until empty or an error."""
    items, page = [], 1
    while True:
        status, body = get(f"{SITE}/wp-json/wp/v2/{endpoint}?per_page=100&page={page}")
        print(f"  {endpoint} page {page}: HTTP {status}")
        if status != 200:
            break
        data = json.loads(body)
        # Past the last page this server answers HTTP 200 with an error object
        # ({"code": "rest_post_invalid_page_number", ...}) instead of a list.
        if not isinstance(data, list) or not data:
            print(f"  {endpoint}: stop ({data.get('code') if isinstance(data, dict) else 'empty'})")
            break
        items.extend(data)
        page += 1
    return items, status


# ---- Step 2: REST API ----
api_status = {}
collections = {}
for ep in ["media", "pages", "posts", "categories", "tags"]:
    items, last = paginate(ep)
    collections[ep] = items
    api_status[ep] = {"items": len(items), "last_status": last}
    (API / f"{ep}.json").write_text(json.dumps(items, indent=2, ensure_ascii=False))

# ---- Step 1: sitemaps ----
sitemap_urls, sitemap_notes = set(), {}
for sm in ["wp-sitemap.xml", "sitemap.xml", "sitemap_index.xml"]:
    status, body = get(f"{SITE}/{sm}")
    text = body.decode("utf-8", "replace")
    (API / f"{sm}.txt").write_text(text)
    locs = re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", text)
    children = [l for l in locs if l.endswith(".xml")]
    for child in children:  # follow child sitemaps if it is an index
        s2, b2 = get(child)
        locs += re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", b2.decode("utf-8", "replace"))
    sitemap_notes[sm] = {"status": status, "locs": len(locs), "children": children}
    sitemap_urls.update(l for l in locs if not l.endswith(".xml"))

spam = sorted(u for u in sitemap_urls if "/products/" in u)
real_from_sitemap = sorted(u for u in sitemap_urls if "/products/" not in u)

# ---- Step 1: menu + footer links on the homepage ----
status, body = get(SITE + "/")
home = body.decode("utf-8", "replace")
links = set(re.findall(r'href="(https://skeinteriors\.com/[^"#?]*)"', home))
skip = re.compile(r"/(wp-content|wp-json|wp-includes|feed|comments/feed|xmlrpc\.php)")
menu_links = {l for l in links if not skip.search(l)}

api_links = {i["link"] for i in collections["pages"] + collections["posts"]}
cat_links = {c["link"] for c in collections["categories"] if c.get("count")}

def norm(u):
    u = u.strip()
    if u.rstrip("/") == SITE:
        return SITE + "/"
    return u if u.endswith("/") else u + "/"

urls = sorted({norm(u) for u in menu_links | api_links | set(real_from_sitemap)})

lines = [
    "# skeinteriors.com — every real public URL",
    "# Sources: homepage menu/footer, WP REST API (pages + posts), sitemaps.",
    "# Generated by scripts/scrape/01-urls-and-media.py",
    "",
]
lines += urls
lines += ["", "# Category archives (for redirects only)"] + sorted(cat_links)
lines += [
    "",
    f"# WARNING: each sitemap lists ~1,108 fake /products/<id> URLs, regenerated on every request",
    f"# ({len(spam)} unique seen across the three sitemap fetches).",
    "# They show Japanese spam to Googlebot and 404 to people (cloaked SEO hack).",
    "# Not crawled. Sample saved in scrape/api/sitemap-spam-sample.txt",
]
(OUT / "urls.txt").write_text("\n".join(lines) + "\n")
(API / "sitemap-spam-sample.txt").write_text("\n".join(spam[:200]) + "\n")

summary = {
    "api": api_status,
    "sitemaps": sitemap_notes,
    "sitemap_spam_urls": len(spam),
    "real_urls": urls,
}
(API / "summary.json").write_text(json.dumps(summary, indent=2))
print(json.dumps(summary, indent=2))
